-- Run this once in a Supabase project's SQL editor.
-- Use only the project's public anon key in the site config.

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  game_id text not null check (game_id ~ '^[a-z0-9-]{1,40}$'),
  display_name text not null check (char_length(trim(display_name)) between 1 and 16),
  score integer not null check (score between 1 and 1000000000),
  packets integer not null default 0 check (packets between 0 and 1000000000),
  seconds integer not null default 0 check (seconds between 0 and 1000000000),
  submission_id text not null unique check (char_length(submission_id) between 8 and 80),
  created_at timestamptz not null default now()
);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "Anyone can read leaderboard scores" on public.leaderboard_scores;
create policy "Anyone can read leaderboard scores"
  on public.leaderboard_scores for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can submit leaderboard scores" on public.leaderboard_scores;
create policy "Anyone can submit leaderboard scores"
  on public.leaderboard_scores for insert
  to anon, authenticated
  with check (
    game_id ~ '^[a-z0-9-]{1,40}$'
    and char_length(trim(display_name)) between 1 and 16
    and score between 1 and 1000000000
    and packets between 0 and 1000000000
    and seconds between 0 and 1000000000
  );

create index if not exists leaderboard_scores_game_score_idx
  on public.leaderboard_scores (game_id, score desc, created_at asc);

-- Scores are intentionally public and anonymous. Moderate or delete rows from
-- the Supabase dashboard if a player abuses the open submission endpoint.
