import assert from "node:assert/strict";
import { newRun, startRun, stepRun, togglePause, HEX_STACK } from "./simulation.js";
const fixed = () => .01;
let state = startRun(fixed);
assert.equal(state.mode, "active");
assert.equal(state.fallEvery, 2, "the opening pace gives players time to aim");
assert.equal(stepRun({ ...state, orientation: 0 }, { rotate: "left" }, 0).orientation, 5);
const paused = togglePause(state);
assert.equal(stepRun(paused, { rotate: "right", drop: true }, 1), paused, "pause freezes timer and input");
assert.equal(togglePause(paused).mode, "active");
state = { ...state, orientation: 0, stacks: [[], ["mint"], [], [], [], ["mint"]], current: "mint", next: "gold", fallAt: .9, fallEvery: 1.2 };
state = stepRun(state, { drop: true }, 0, fixed);
assert.equal(state.cleared, 3, "three connected tiles clear across neighboring sides");
assert.equal(state.score, 90);
assert.equal(state.stacks.flat().length, 0);
state = { ...startRun(fixed), orientation: 0, stacks: [["mint", "mint"], [], [], [], [], []], current: "coral", next: "gold", fallEvery: 1.2 };
state = stepRun(state, { drop: true }, 0, fixed);
assert.equal(state.cleared, 0, "different colors do not clear");
assert.equal(state.stacks[0].length, 3);
state = { ...startRun(fixed), orientation: 0, stacks: [["mint"], ["coral", "mint"], [], [], [], []], current: "mint", next: "gold", fallEvery: 1.2 };
state = stepRun(state, { drop: true }, 0, fixed);
assert.equal(state.cleared, 0, "matching colors on separated outer spokes do not clear");
state = { ...startRun(fixed), orientation: 3, stacks: [[], [], [], ["mint", "mint"], [], []], current: "mint", next: "gold", fallEvery: 1.2 };
state = stepRun(state, { drop: true }, 0, fixed);
assert.equal(state.cleared, 3, "three matching tiles along one spoke clear");
state = { ...startRun(fixed), cleared: 12, orientation: 0, stacks: Array.from({ length: 6 }, () => []), current: "mint", next: "gold", fallEvery: 1.2 };
state = stepRun(state, { drop: true }, 0, fixed);
assert.equal(state.level, 2);
assert.ok(state.fallEvery < 2);
state = { ...startRun(fixed), orientation: 2, stacks: Array.from({ length: 6 }, (_, side) => side === 2 ? Array(HEX_STACK.maxDepth).fill("mint") : []), current: "gold", next: "mint", fallEvery: 1.2 };
assert.equal(stepRun(state, { drop: true }, 0, fixed).mode, "over", "overflow ends the round");
assert.equal(newRun(fixed).mode, "ready");
console.log("Hex Stack simulation checks passed.");
